language: python
sudo: false
python: 
  - 2.7
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7 
    - dist: xenial
    - sudo: true   
before_install:
  - python --version
  - python -c \"import struct; print(struct.calcsize('P') * 8)\" 
  - pip install --upgrade pip 
  - pip install codecov pytest pytest-cov numpy scipy coverage
install: python setup.py install
script: 
  - python -m pytest -v tests/
  - coverage run -m pytest tests/  
after_success:
  codecov
