language: python
sudo: false
python: 
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"  
before_install: 
  pip install codecov pytest pytest-cov numpy scipy
install: python setup.py install
script: pytest --cov=./
after_success:
  codecov
